## **Assignment No -7**

---

**Name** - More Payal Balasaheb .
**Roll No** - EN23107080 .
**Batch** - A

---

**Title** - Word embedding: Implement word embeddings for the English language to analyze word representations and their semantic relationships (Word2Vec/GloVe/fastText).

In [1]:
pip install gensim nltk

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.0.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 60.7 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [6]:
import nltk
from nltk.tokenize import word_tokenize
import string

In [13]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

## **Initial model building with Simple input**

In [14]:
text_data = [
    "king is a strong man",
    "queen is a wise woman",
    "boy is a young man",
    "girl is a young woman",
    "prince is the son of the king",
    "princess is the daughter of the queen",
    "man and woman are adults",
    "boy and girl are children"
]

In [15]:
sentences = []

for sentence in text_data:
    tokens = word_tokenize(sentence.lower())
    sentences.append(tokens)

print(sentences)

[['king', 'is', 'a', 'strong', 'man'], ['queen', 'is', 'a', 'wise', 'woman'], ['boy', 'is', 'a', 'young', 'man'], ['girl', 'is', 'a', 'young', 'woman'], ['prince', 'is', 'the', 'son', 'of', 'the', 'king'], ['princess', 'is', 'the', 'daughter', 'of', 'the', 'queen'], ['man', 'and', 'woman', 'are', 'adults'], ['boy', 'and', 'girl', 'are', 'children']]

**1) Word2vec model**

In [17]:
from gensim.models import Word2Vec

word2vec_model = Word2Vec(sentences=sentences,vector_size=50,window=3,min_count=1)

In [22]:
word2vec_model.save("word2vec_simple.model")

In [23]:
print(word2vec_model.wv['king'])

[ 1.62617061e-02 -8.91195424e-03 -2.13885913e-03  2.01333570e-03
 -3.77513759e-04  2.29952740e-03  1.22290272e-02 -3.82634171e-05
 -6.49430929e-03 -3.01940856e-03  1.17932027e-02  3.03019909e-03
 -1.44841056e-03  1.86656304e-02 -9.84004978e-03 -1.68058684e-03
  1.83532089e-02  1.35018732e-02  3.00353277e-03 -1.77686047e-02
  2.29624542e-03 -4.58001345e-03  1.87399164e-02  2.42063962e-03
  2.97887367e-03  4.81249671e-03 -3.66971875e-03 -9.99547262e-03
  4.60460025e-04 -4.02657641e-03  1.32046631e-02  1.78802367e-02
 -1.35146279e-03  5.94991539e-03 -1.22152865e-02  3.39886523e-03
 -1.38518056e-02 -1.73875000e-02 -1.18045248e-02 -1.79105382e-02
  1.45571595e-02 -1.15457894e-02  1.65504012e-02 -1.44828148e-02
  6.84856856e-03  1.93490554e-02 -1.55713325e-02 -1.98924951e-02
 -8.65845848e-03 -5.36803389e-03]

In [24]:
word2vec_model.wv.most_similar('king')

[('woman', 0.19006991386413574),
 ('adults', 0.18862654268741608),
 ('queen', 0.17435936629772186),
 ('of', 0.11523938179016113),
 ('are', 0.10158563405275345),
 ('the', 0.08072591572999954),
 ('is', 0.040662799030542374),
 ('strong', 0.02493080496788025),
 ('prince', 0.00038622142164967954),
 ('man', -0.023145563900470734)]

**2) FastText model**

In [20]:
from gensim.models import FastText

fasttext_model = FastText(sentences=sentences,vector_size=50,window=3,min_count=1)

In [25]:
fasttext_model.save("fasttext_simple.model")

In [26]:
print(fasttext_model.wv['kingly'])

[ 1.8430559e-03 -2.1648547e-03 -1.9256618e-04 -1.9204335e-03
  1.2488740e-03 -3.1675780e-03 -2.4523197e-03  7.7731634e-04
  2.7169113e-04 -3.8701590e-04 -8.3620369e-04 -1.1744327e-03
 -2.6224323e-03  3.1014148e-04 -7.1572787e-05 -6.2730303e-04
  2.5231966e-03  8.6668192e-04  5.0769426e-04 -3.1734267e-03
  2.2111172e-03 -2.7514475e-03  6.3829927e-04 -1.9310585e-03
  3.1331489e-05  3.9480766e-03 -1.8269670e-03  2.3176766e-03
  1.8428148e-03  1.0557438e-03  1.7575832e-03 -1.8525182e-03
 -1.3579624e-03  5.3523122e-03  4.2859213e-03 -4.9976921e-03
  6.6411580e-05 -9.2623755e-05 -2.9094189e-03  8.3470927e-04
  3.5311995e-04  4.4168644e-03 -2.3224470e-03  1.3569541e-03
  1.2624537e-03 -6.2926050e-04  1.3790936e-04  3.6517731e-04
  4.3159735e-04  1.7747182e-03]

## **Model Building with dataset**

In [52]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [60]:
df = pd.read_json("reviews_Cell_Phones_and_Accessories_5.json.gz", lines=True)

In [61]:
df

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014"
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014"
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014"
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013"
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013"
...,...,...,...,...,...,...,...,...,...
194434,A1YMNTFLNDYQ1F,B00LORXVUE,eyeused2loveher,"[0, 0]",Works great just like my original one. I reall...,5,This works just perfect!,1405900800,"07 21, 2014"
194435,A15TX8B2L8B20S,B00LORXVUE,Jon Davidson,"[0, 0]",Great product. Great packaging. High quality a...,5,Great replacement cable. Apple certified,1405900800,"07 21, 2014"
194436,A3JI7QRZO1QG8X,B00LORXVUE,Joyce M. Davidson,"[0, 0]","This is a great cable, just as good as the mor...",5,Real quality,1405900800,"07 21, 2014"
194437,A1NHB2VC68YQNM,B00LORXVUE,Nurse Farrugia,"[0, 0]",I really like it becasue it works well with my...,5,I really like it becasue it works well with my...,1405814400,"07 20, 2014"
194438,A1AG6U022WHXBF,B00LORXVUE,Trisha Crocker,"[0, 0]","product as described, I have wasted a lot of m...",5,I have wasted a lot of money on cords,1405900800,"07 21, 2014"

In [62]:
df.shape

(194439, 9)

In [63]:
df.isnull().sum()

reviewerID           0
asin                 0
reviewerName      3519
helpful              0
reviewText           0
overall              0
summary              0
unixReviewTime       0
reviewTime           0
dtype: int64

In [64]:
df = df["reviewText"]

In [65]:
df

0         They look good and stick good! I just don't li...
1         These stickers work like the review says they ...
2         These are awesome and make my phone look so st...
3         Item arrived in great time and was in perfect ...
4         awesome! stays on, and looks great. can be use...
                                ...
194434    Works great just like my original one. I reall...
194435    Great product. Great packaging. High quality a...
194436    This is a great cable, just as good as the mor...
194437    I really like it becasue it works well with my...
194438    product as described, I have wasted a lot of m...
Name: reviewText, Length: 194439, dtype: object

In [66]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

**Preprocessing of dataset**

In [67]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_review(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-z\s]", "", text) 
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    tokens = [lemmatizer.lemmatize(w) for w in tokens]
    return tokens

In [70]:
processed_reviews = df.apply(preprocess_review)

In [71]:
print(processed_reviews.iloc[0])

['look', 'good', 'stick', 'good', 'dont', 'like', 'rounded', 'shape', 'always', 'bumping', 'siri', 'kept', 'popping', 'irritating', 'wont', 'buy', 'product', 'like']

In [72]:
sentences = processed_reviews.tolist()

**1) word2text model**

In [73]:
word2vec_model = Word2Vec(sentences=sentences,vector_size=100,window=5,min_count=5,workers=4)

In [74]:
word2vec_model.save("reviews_word2vec.model")

In [75]:
word2vec_model.wv["battery"]

array([ 1.3536649e+00,  1.0539993e+00,  4.7618771e-01, -2.2348099e+00,
       -1.4406061e+00,  4.3126968e-01,  1.1165924e+00, -1.1869452e+00,
        1.2427161e+00, -3.0091238e+00,  6.5731883e-02, -1.3844219e-01,
       -9.5127332e-01,  1.1022738e+00, -8.1806725e-01, -5.0142426e+00,
       -1.5569643e+00, -4.7550774e-01, -2.2126040e+00, -5.4889661e-01,
       -1.3861885e+00,  6.1157984e-01,  6.6424394e-01,  3.7964265e+00,
       -1.2871428e-01, -1.9089598e-02,  2.1059902e+00, -2.5843320e+00,
        1.3788481e+00,  7.1784323e-01, -2.6949410e+00, -1.7354732e+00,
       -5.9440833e-01, -2.5626521e+00,  8.0875957e-01,  2.9724419e+00,
       -7.1161473e-01,  1.8684782e+00, -2.4351272e-01, -7.0613325e-01,
        2.0435596e+00,  2.0852664e+00, -9.6960627e-02, -3.6517277e-01,
       -1.3491678e+00,  2.2469599e+00,  8.2050496e-01, -6.2107348e-01,
        2.3025727e+00,  1.0459337e-01,  9.1025317e-01, -9.1521639e-01,
        2.4601977e+00,  5.5489314e-01, -2.5750949e+00,  3.2203054e-01,
        1.8016177e+00,  2.6080093e-01, -1.0172707e+00, -1.9480982e+00,
        2.9025650e+00, -1.5242227e+00,  9.1426909e-01, -2.3318570e+00,
        1.8919463e+00,  3.2459612e+00, -2.2184925e+00, -1.2621392e+00,
       -7.3604465e-02, -4.9655922e-03, -4.8175845e-01, -1.6514648e-01,
        2.8726420e-01,  1.2957387e+00, -1.3650088e+00, -3.0450392e-01,
        6.4142138e-01, -4.9533558e-01,  2.1737132e+00,  1.7155583e+00,
        8.2866031e-01,  1.2956837e+00,  2.1851642e+00, -1.1912479e+00,
       -4.0852204e-01, -2.0662966e+00, -6.4178592e-01, -5.1401198e-01,
        1.3360216e-01, -2.7957329e-01, -8.6160463e-01, -6.8735003e-01,
       -2.9524894e+00,  3.6820033e-01,  1.0929831e+00,  1.0736079e+00,
       -2.9853623e+00, -2.1897437e-02, -1.9310179e+00, -2.5206921e+00],
      dtype=float32)

**Similarity of word**

In [76]:
word2vec_model.wv.most_similar("battery")

[('batter', 0.9025763273239136),
 ('batt', 0.7757960557937622),
 ('batteryi', 0.6846150755882263),
 ('batterythe', 0.6619258522987366),
 ('batteryit', 0.6138152480125427),
 ('itbattery', 0.5902256369590759),
 ('batterythis', 0.5873705744743347),
 ('mah', 0.5860506892204285),
 ('juice', 0.5790018439292908),
 ('nimh', 0.5767474174499512)]

In [91]:
word2vec_model.wv.most_similar("bad")

[('terrible', 0.6979544162750244),
 ('horrible', 0.6532760858535767),
 ('good', 0.6206117868423462),
 ('ok', 0.5962848663330078),
 ('okay', 0.5642291903495789),
 ('poor', 0.5485679507255554),
 ('weird', 0.5350766181945801),
 ('fault', 0.5275195837020874),
 ('awful', 0.5254069566726685),
 ('funny', 0.5239130854606628)]

In [92]:
word2vec_model.wv.most_similar("cheap")

[('cheep', 0.7197719216346741),
 ('flimsy', 0.6800519824028015),
 ('cheesy', 0.6658259034156799),
 ('crappy', 0.6049144268035889),
 ('cheapy', 0.5935932397842407),
 ('alright', 0.5848827958106995),
 ('cheaply', 0.5682703256607056),
 ('fragile', 0.567979633808136),
 ('brittle', 0.5438405275344849),
 ('legit', 0.5405962467193604)]

**Similarity between two words**

In [77]:
similarity = word2vec_model.wv.similarity("battery", "charger")
print("Word2Vec similarity:", similarity)

Word2Vec similarity: 0.4666846

In [81]:
pairs = [
    ("battery", "charger"),
    ("phone", "case"),
    ("good", "bad"),
    ("screen", "display")
]

for w1, w2 in pairs:
    print(w1, w2,word2vec_model.wv.similarity(w1, w2))

battery charger 0.4666846
phone case 0.37265992
good bad 0.6206117
screen display 0.5259698

**2) fasttext model**

In [82]:
fasttext_model = FastText(sentences=sentences,vector_size=100,window=5,min_count=5,workers=4)

In [83]:
fasttext_model.save("reviews_fasttext.model")

**Similar word**

In [88]:
fasttext_model.wv.most_similar("good")

[('goodgood', 0.9879930019378662),
 ('goodmy', 0.9262255430221558),
 ('gooda', 0.923001229763031),
 ('goodi', 0.9183791875839233),
 ('goodso', 0.9148955345153809),
 ('goodgreat', 0.9130080342292786),
 ('goodno', 0.9072812795639038),
 ('goood', 0.9060505032539368),
 ('goodas', 0.9014120697975159),
 ('goodif', 0.897287905216217)]

In [89]:
fasttext_model.wv.most_similar("bad")

[('badmy', 0.8833112716674805),
 ('badi', 0.8824390769004822),
 ('bada', 0.8780300617218018),
 ('badif', 0.8473835587501526),
 ('goodbad', 0.8187528252601624),
 ('badin', 0.7934190630912781),
 ('badbut', 0.7601362466812134),
 ('badit', 0.6886236667633057),
 ('horriblei', 0.6367409825325012),
 ('badits', 0.6333974003791809)]

In [90]:
fasttext_model.wv["batterylife"]

array([-0.3944538 , -0.3398224 ,  0.2987683 , -0.57832193,  0.19271997,
       -0.8834837 , -1.0897353 ,  2.5730705 ,  0.66679066,  0.11449029,
       -0.06780602,  1.1474771 , -0.36405453, -0.02605002, -0.16856445,
       -0.41229615, -0.18607189,  1.6688852 , -1.2978709 , -0.6158691 ,
        0.3349213 ,  0.43835044, -0.32043627, -0.25436926, -1.4872317 ,
       -0.73148996,  1.2012037 , -0.00871051,  0.30808878, -0.3193429 ,
       -0.41219682,  0.339837  ,  0.7903069 , -0.86126286,  1.6711085 ,
        0.8733887 ,  0.28570482, -0.08619335,  1.5366399 ,  0.00822847,
       -0.46653512, -1.3874947 , -1.2477622 ,  0.46385866,  0.96915907,
        2.3136337 ,  0.51412266, -0.28050286, -0.20484887, -0.95359164,
       -1.2856601 , -1.0853102 , -0.37273705,  0.44378847,  0.6922835 ,
       -0.50194454,  2.437706  ,  2.2540588 , -2.5821123 , -1.1938944 ,
        0.11642587, -0.11167578,  0.18520643, -0.63003176, -0.810032  ,
        0.11911711,  0.8050819 ,  0.11900938,  0.9287264 , -0.02203366,
        0.45644525, -0.69002575, -1.051732  ,  0.77578396, -0.02463755,
       -0.36798254,  0.95431453,  0.46227422,  0.00712896, -0.40660173,
        1.0524617 , -0.6270921 ,  0.4650238 , -1.3168586 , -1.7049909 ,
        0.30344942,  0.90510136, -1.034461  ,  1.0665592 , -0.9356026 ,
        0.4350232 ,  0.42128983,  0.83025753,  0.5711509 , -0.04849938,
       -0.39950657, -0.41205773, -0.4515575 ,  1.3953449 , -1.0035435 ],
      dtype=float32)

**Similarity between words**

In [86]:
similarity = fasttext_model.wv.similarity("battery", "charger")
print("fastText similarity:", similarity)

fastText similarity: 0.53215146

In [93]:
pairs = [
    ("battery", "charger"),
    ("phone", "case"),
    ("good", "bad"),
    ("screen", "display")
]

for w1, w2 in pairs:
    print(w1, w2,word2vec_model.wv.similarity(w1, w2))

battery charger 0.4666846
phone case 0.37265992
good bad 0.6206117
screen display 0.5259698